name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - scikit-learn==0.23.2
      - mlflow==1.26.1
      - pandas
      - /dbfs/FileStore/tables/testWheel-1.0-py2.py3-none-any.whl
